Update infrastructure-python-packaging.rst
Proposed method to bypass the proxy doesn't work it throws a TypeError: 
Either the --wheelsproxy argument or a WHEELSPROXY_URL environment variable are required.
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'